### ISSUE TITLE
api_aes_gcm

### ISSUE THREAD

**Issue by william3434** [rafael-santiago/linux-crypto-api-aes-gcm-min-sample#1]
Hi Rafael! Thank you for sharing the example, it clears my mind, and i try to flow your steps, but i got faild when i called the function: **g_tfm = crypto_alloc_aead("gcm(aes)", 0, 0)**, is there any preparation I need to do before calling this function?
![image](https://user-images.githubusercontent.com/86050477/184585770-a2174ae6-9269-424b-8c84-5510b1ab565c.png)
![image](https://user-images.githubusercontent.com/86050477/184585862-23ad3351-3dc0-4dbf-8810-ced4e041bb69.png)

**Comment by rafael-santiago** [comment]
Hi William, you are welcome, I am glad that it is being a shortcut for someone in opposite to what I had to face before. Which kernel version you are using? Does your kernel support ``AES/AEAD`` or was it built with ``kernel crypto api`` support?

**Comment by william3434** [comment]
> 
Hi Rafael! thank you for your reply, that reminds me a lot. I'm using OpenWRT with kernel version 4.4.198, and i found that GCM was not compiled into the kernel. And i'm recompiling the kernel, and i will try again.

**Comment by rafael-santiago** [comment]
Nice! Let me know your results. Thanks for replying!

**Comment by william3434** [comment]
> Nice! Let me know your results. Thanks for replying!
Rafael, good news, it worked! thank you so much!

**Comment by rafael-santiago** [comment]
> > Nice! Let me know your results. Thanks for replying!
> > Rafael, good news, it worked! thank you so much!

Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!

**Comment by william3434** [comment]
Hi Rafael, good day! This example really helped me a lot. I also want to ask if this example can be applied to the scene with associated data parameter. How do you pass this parameter, if applicable? And in the example you shared, I noticed that you set the length of associated data to 0.
![image](https://user-images.githubusercontent.com/86050477/185335588-ffe5ac76-ea42-4c92-8892-4de3c8181724.png)

**Comment by rafael-santiago** [comment]
Hi William, yes it can be extended. Associated data is only about a plain data that is not secret but must be taken into consideration when verifying the cryptogram integrity. I meant the whole data was not tampered with. It is commonly used with IPSec for example, the aad usually is information about used ports.

**Comment by william3434** [comment]
> Hi William, yes it can be extended. Associated data is only about a plain data that is not secret but must be taken into consideration when verifying the cryptogram integrity. I meant the whole data was not tampered with. It is commonly used with IPSec for example, the aad usually is information about used ports.
ok Rafael, i will try.

**Comment by william3434** [comment]
> Hi William, yes it can be extended. Associated data is only about a plain data that is not secret but must be taken into consideration when verifying the cryptogram integrity. I meant the whole data was not tampered with. It is commonly used with IPSec for example, the aad usually is information about used ports.

ok Rafael, i will try.

**Comment by william3434** [comment]
> > > Nice! Let me know your results. Thanks for replying!
> > > Rafael, good news, it worked! thank you so much!
> 
> Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!

Hi Rafael, good day, have you tested in the 5.4 kernel version?

**Comment by rafael-santiago** [comment]
> > > > Nice! Let me know your results. Thanks for replying!
> > > > Rafael, good news, it worked! thank you so much!
> > 
> > 
> > Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!
> 
> Hi Rafael, good day, have you tested in the 5.4 kernel version?

Hi @william3434 I have tested on some ``5.x`` versions but I do not remember which. Since I am a ``Slackware`` (❤️) user I did some workarounds for my state of things with ``4.n`` kernel and tested on a plushy Ubuntu VM (``5.13``) and worked fine. However I would not be surprised if it is broken on some ``5.x`` kernels because the Linux kernel backward compatibility is pretty bad compared with other kernels. They move fast but break a lot of things without minding much about "out of tree" kernel developers, they mind only about userland in the most, this is an issue if you want to support many kernel versions from your "out of tree" stuff.

Now a true horror story:

Last year a was facing a kernel panic in a kernel module of mine that was compiled with no warnings. The kernel module build was fine, but during the system tests 💥 🔥 💀 .

The problem was that from a kernel version to another the prototype of a such well-basic kernel system call (``kernel_read``) has changed in a pretty silly way (taking into consideration the basis of ``C`` language):
- the older version was expecting: a file pointer, **a flag**, a buffer and, the size of this buffer.
- the newer version was expecting: a file pointer, a bufer, the size of this buffer and **the flag**.

What is the problem? Well the flag is commonly passed as zero and due to it in the new kernel zero was being promoted to  ``NULL`` (this is legit in ``C`` it is not a problem when you are conscious about your choice) and the code that was valid in the old kernel has become a bomb accessing null pointer in ``ring0``. Now imagine a scenario where the user has just updated her/his kernel and recompile the module: 💣 💥 ☠️. With it you start understanding why kernel modules are not as windows drivers that you can load it from a Windows version to others (shh!...). If you want to change the prototype of a such basic function touching a problem that goes beyond the kernel design ending up in ``C`` design choices you must start doing a double-check inside kernel specially because nowadays you have a bunch of out-of-tree stuff running in people's kernel out there. Personally, I found this prototype changing decision a little sloopy and naïve about all bad implications of it. Still, imagine a naïve manufacturer that downloads its code inside the user machine compiles it and replaces the new explosive kernel module. This is why seeing ``Ubuntu`` folks refreshing their kernels every single week makes me cringe a lot, if you grasp into those well basic incompatibilities, if you face so near those real problems that no one openly discusses or if you try to discuss and see that people will just run ostrich algorithm, you start stick with what works for you and forgot hispters/fashion kernel updatings, this is why I love ``Slackware``. Now, technically speaking as a programmer and eternal learner, those among other bad things in Linux kernel development made me be very skeptic about dedicating many hours in this kernel. Nowadays I prefer doing my stuff on Windows or BSD (two kernels that are very stable from a version to another) and  adapt some stuff for Linux, it is more time saver! I learned a lot grasp into Linux kernel source code, but nowadays it has becoming a bit messy with so many backward compatibility breakings inside kernel, it is pretty sad. Takeways about it? Well, besides never trust on new kernel releases, test your stuff before shipping it, never ever build it on user's machine without knowing that it is really working fine in that ``specific`` kernel version. Now, remember the horror story, even built and tested on older kernels and in the current new one, it does not ensure that it cannot explode in the newer one. It is better to explode in front of your face instead of your customer, so run good and impartial system tests! (sometimes ``KVM`` won't save you, too...)

**Comment by william3434** [comment]
> > > > > Nice! Let me know your results. Thanks for replying!
> > > > > Rafael, good news, it worked! thank you so much!
> > > 
> > > 
> > > Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!
> > 
> > 
> > Hi Rafael, good day, have you tested in the 5.4 kernel version?
> 
> Hi @william3434 I have tested on some `5.x` versions but I do not remember which. Since I am a `Slackware` (❤️) user I did some workarounds for my state of things with `4.n` kernel and tested on a plushy Ubuntu VM (`5.13`) and worked fine. However I would not be surprised if it is broken on some `5.x` kernels because the Linux kernel backward compatibility is pretty bad compared with other kernels. They move fast but break a lot of things without minding much about "out of tree" kernel developers, they mind only about userland in the most, this is an issue if you want to support many kernel versions from your "out of tree" stuff.
> 
> Now a true horror story:
> 
> Last year a was facing a kernel panic in a kernel module of mine that was compiled with no warnings. The kernel module build was fine, but during the system tests 💥 🔥 💀 .
> 
> The problem was that from a kernel version to another the prototype of a such well-basic kernel system call (`kernel_read`) has changed in a pretty silly way (taking into consideration the basis of `C` language):
> 
> * the older version was expecting: a file pointer, **a flag**, a buffer and, the size of this buffer.
> * the newer version was expecting: a file pointer, a bufer, the size of this buffer and **the flag**.
> 
> What is the problem? Well the flag is commonly passed as zero and due to it in the new kernel zero was being promoted to `NULL` (this is legit in `C` it is not a problem when you are conscious about your choice) and the code that was valid in the old kernel has become a bomb accessing null pointer in `ring0`. Now imagine a scenario where the user has just updated her/his kernel and recompile the module: 💣 💥 ☠️. With it you start understanding why kernel modules are not as windows drivers that you can load it from a Windows version to others (shh!...). If you want to change the prototype of a such basic function touching a problem that goes beyond the kernel design ending up in `C` design choices you must start doing a double-check inside kernel specially because nowadays you have a bunch of out-of-tree stuff running in people's kernel out there. Personally, I found this prototype changing decision a little sloopy and naïve about all bad implications of it. Still, imagine a naïve manufacturer that downloads its code inside the user machine compiles it and replaces the new explosive kernel module. This is why seeing `Ubuntu` folks refreshing their kernels every single week makes me cringe a lot, if you grasp into those well basic incompatibilities, if you face so near those real problems that no one openly discusses or if you try to discuss and see that people will just run ostrich algorithm, you start stick with what works for you and forgot hispters/fashion kernel updatings, this is why I love `Slackware`. Now, technically speaking as a programmer and eternal learner, those among other bad things in Linux kernel development made me be very skeptic about dedicating many hours in this kernel. Nowadays I prefer doing my stuff on Windows or BSD (two kernels that are very stable from a version to another) and adapt some stuff for Linux, it is more time saver! I learned a lot grasp into Linux kernel source code, but nowadays it has becoming a bit messy with so many backward compatibility breakings inside kernel, it is pretty sad. Takeways about it? Well, besides never trust on new kernel releases, test your stuff before shipping it, never ever build it on user's machine without knowing that it is really working fine in that `specific` kernel version. Now, remember the horror story, even built and tested on older kernels and in the current new one, it does not ensure that it cannot explode in the newer one. It is better to explode in front of your face instead of your customer, so run good and impartial system tests! (sometimes `KVM` won't save you, too...)

Hi Rafael, thank you for your sharing and valuable experience. I also have deep feelings about the compatibility of the LINUX kernel, and now i'am facing  a kernel panic in a kernel module that was compiled with no warnings!!!! The horror story that are happening....

**Comment by rafael-santiago** [comment]
> > > > > > Nice! Let me know your results. Thanks for replying!
> 
> > > > > > Rafael, good news, it worked! thank you so much!
> 
> > > > 
> 
> > > > 
> 
> > > > Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!
> 
> > > 
> 
> > > 
> 
> > > Hi Rafael, good day, have you tested in the 5.4 kernel version?
> 
> > 
> 
> > Hi @william3434 I have tested on some `5.x` versions but I do not remember which. Since I am a `Slackware` (❤️) user I did some workarounds for my state of things with `4.n` kernel and tested on a plushy Ubuntu VM (`5.13`) and worked fine. However I would not be surprised if it is broken on some `5.x` kernels because the Linux kernel backward compatibility is pretty bad compared with other kernels. They move fast but break a lot of things without minding much about "out of tree" kernel developers, they mind only about userland in the most, this is an issue if you want to support many kernel versions from your "out of tree" stuff.
> 
> > 
> 
> > Now a true horror story:
> 
> > 
> 
> > Last year a was facing a kernel panic in a kernel module of mine that was compiled with no warnings. The kernel module build was fine, but during the system tests 💥 🔥 💀 .
> 
> > 
> 
> > The problem was that from a kernel version to another the prototype of a such well-basic kernel system call (`kernel_read`) has changed in a pretty silly way (taking into consideration the basis of `C` language):
> 
> > 
> 
> > * the older version was expecting: a file pointer, **a flag**, a buffer and, the size of this buffer.
> 
> > * the newer version was expecting: a file pointer, a bufer, the size of this buffer and **the flag**.
> 
> > 
> 
> > What is the problem? Well the flag is commonly passed as zero and due to it in the new kernel zero was being promoted to `NULL` (this is legit in `C` it is not a problem when you are conscious about your choice) and the code that was valid in the old kernel has become a bomb accessing null pointer in `ring0`. Now imagine a scenario where the user has just updated her/his kernel and recompile the module: 💣 💥 ☠️. With it you start understanding why kernel modules are not as windows drivers that you can load it from a Windows version to others (shh!...). If you want to change the prototype of a such basic function touching a problem that goes beyond the kernel design ending up in `C` design choices you must start doing a double-check inside kernel specially because nowadays you have a bunch of out-of-tree stuff running in people's kernel out there. Personally, I found this prototype changing decision a little sloopy and naïve about all bad implications of it. Still, imagine a naïve manufacturer that downloads its code inside the user machine compiles it and replaces the new explosive kernel module. This is why seeing `Ubuntu` folks refreshing their kernels every single week makes me cringe a lot, if you grasp into those well basic incompatibilities, if you face so near those real problems that no one openly discusses or if you try to discuss and see that people will just run ostrich algorithm, you start stick with what works for you and forgot hispters/fashion kernel updatings, this is why I love `Slackware`. Now, technically speaking as a programmer and eternal learner, those among other bad things in Linux kernel development made me be very skeptic about dedicating many hours in this kernel. Nowadays I prefer doing my stuff on Windows or BSD (two kernels that are very stable from a version to another) and adapt some stuff for Linux, it is more time saver! I learned a lot grasp into Linux kernel source code, but nowadays it has becoming a bit messy with so many backward compatibility breakings inside kernel, it is pretty sad. Takeways about it? Well, besides never trust on new kernel releases, test your stuff before shipping it, never ever build it on user's machine without knowing that it is really working fine in that `specific` kernel version. Now, remember the horror story, even built and tested on older kernels and in the current new one, it does not ensure that it cannot explode in the newer one. It is better to explode in front of your face instead of your customer, so run good and impartial system tests! (sometimes `KVM` won't save you, too...)
> 
> 
> 
> Hi Rafael, thank you for your sharing and valuable experience. I also have deep feelings about the compatibility of the LINUX kernel, and now i'am facing  a kernel panic in a kernel module that was compiled with no warnings!!!! The horror story that are happening....

Hmmm... Maybe it can be another backward compatibility issue. Try to inspect the callstack, maybe just by running dmesg just after the problem (when there is no reboot) can give you some clue.

**Comment by rafael-santiago** [comment]
> > > > > > Nice! Let me know your results. Thanks for replying!
> > > > > > Rafael, good news, it worked! thank you so much!
> > > > 
> > > > 
> > > > Good to know, that we do not have other incompatibility between kernel versions! You are welcome! I think your results closes this issue, any other let me know. Happy coding!
> > > 
> > > 
> > > Hi Rafael, good day, have you tested in the 5.4 kernel version?
> > 
> > 
> > Hi @william3434 I have tested on some `5.x` versions but I do not remember which. Since I am a `Slackware` (❤️) user I did some workarounds for my state of things with `4.n` kernel and tested on a plushy Ubuntu VM (`5.13`) and worked fine. However I would not be surprised if it is broken on some `5.x` kernels because the Linux kernel backward compatibility is pretty bad compared with other kernels. They move fast but break a lot of things without minding much about "out of tree" kernel developers, they mind only about userland in the most, this is an issue if you want to support many kernel versions from your "out of tree" stuff.
> > Now a true horror story:
> > Last year a was facing a kernel panic in a kernel module of mine that was compiled with no warnings. The kernel module build was fine, but during the system tests 💥 🔥 💀 .
> > The problem was that from a kernel version to another the prototype of a such well-basic kernel system call (`kernel_read`) has changed in a pretty silly way (taking into consideration the basis of `C` language):
> > 
> > * the older version was expecting: a file pointer, **a flag**, a buffer and, the size of this buffer.
> > * the newer version was expecting: a file pointer, a bufer, the size of this buffer and **the flag**.
> > 
> > What is the problem? Well the flag is commonly passed as zero and due to it in the new kernel zero was being promoted to `NULL` (this is legit in `C` it is not a problem when you are conscious about your choice) and the code that was valid in the old kernel has become a bomb accessing null pointer in `ring0`. Now imagine a scenario where the user has just updated her/his kernel and recompile the module: 💣 💥 ☠️. With it you start understanding why kernel modules are not as windows drivers that you can load it from a Windows version to others (shh!...). If you want to change the prototype of a such basic function touching a problem that goes beyond the kernel design ending up in `C` design choices you must start doing a double-check inside kernel specially because nowadays you have a bunch of out-of-tree stuff running in people's kernel out there. Personally, I found this prototype changing decision a little sloopy and naïve about all bad implications of it. Still, imagine a naïve manufacturer that downloads its code inside the user machine compiles it and replaces the new explosive kernel module. This is why seeing `Ubuntu` folks refreshing their kernels every single week makes me cringe a lot, if you grasp into those well basic incompatibilities, if you face so near those real problems that no one openly discusses or if you try to discuss and see that people will just run ostrich algorithm, you start stick with what works for you and forgot hispters/fashion kernel updatings, this is why I love `Slackware`. Now, technically speaking as a programmer and eternal learner, those among other bad things in Linux kernel development made me be very skeptic about dedicating many hours in this kernel. Nowadays I prefer doing my stuff on Windows or BSD (two kernels that are very stable from a version to another) and adapt some stuff for Linux, it is more time saver! I learned a lot grasp into Linux kernel source code, but nowadays it has becoming a bit messy with so many backward compatibility breakings inside kernel, it is pretty sad. Takeways about it? Well, besides never trust on new kernel releases, test your stuff before shipping it, never ever build it on user's machine without knowing that it is really working fine in that `specific` kernel version. Now, remember the horror story, even built and tested on older kernels and in the current new one, it does not ensure that it cannot explode in the newer one. It is better to explode in front of your face instead of your customer, so run good and impartial system tests! (sometimes `KVM` won't save you, too...)
> 
> Hi Rafael, thank you for your sharing and valuable experience. I also have deep feelings about the compatibility of the LINUX kernel, and now i'am facing a kernel panic in a kernel module that was compiled with no warnings!!!! The horror story that are happening....

Maybe you should try to adapt [this compiler directive](https://github.com/rafael-santiago/linux-crypto-api-aes-gcm-min-sample/blob/main/src/aes_gcm.c#L18) to also try to include this workaround for your kernel version. Who knows it can solve your issue.
